### ISSUE TITLE
grpcreplay_test.go fails on Fedora Rawhide i686 and ppc64le

### ISSUE THREAD

**Issue by flyn-org** [google/go-replayers#61]
I maintain the golang-github-google-replayers package for Fedora. I have found that the checks in the build process fail on i686 and ppc64le. It appears what is expected in the test output is, e.g., `name:  "a"` but what is received is `name: "a"` (note the double space in the former and the single space in the latter). I am not sure if this is a problem in golang-github-google-replayers, in one of the packages replayers depends on, or the build environment. Here is the complete error message on ppc64le:
```
Testing    in: /builddir/build/BUILD/golang-github-google-replayers-1.2.0-build/go-replayers-httpreplay-v1.2.0/_build/src
         PATH: /builddir/build/BUILD/golang-github-google-replayers-1.2.0-build/go-replayers-httpreplay-v1.2.0/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/golang-github-google-replayers-1.2.0-build/go-replayers-httpreplay-v1.2.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags " -X github.com/google/go-replayers/version.tag=httpreplay/v1.2.0 -X github.com/google/go-replayers/version=1.2.0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  '"
      testing: github.com/google/go-replayers
github.com/google/go-replayers/grpcreplay
--- FAIL: TestFprintReader (0.00s)
    grpcreplay_test.go:636: got:
        initial state: "\x01\x02\x03"
        #1: kind: REQUEST, method: /intstore.IntStore/Set, ref index: 0, message:
        name: "a"
        value: 1
        #2: kind: RESPONSE, method: , ref index: 1, message:
        #3: kind: REQUEST, method: /intstore.IntStore/Get, ref index: 0, message:
        name: "a"
        #4: kind: RESPONSE, method: , ref index: 3, message:
        name: "a"
        value: 1
        #5: kind: REQUEST, method: /intstore.IntStore/Get, ref index: 0, message:
        name: "x"
        #6: kind: RESPONSE, method: , ref index: 5, error: rpc error: code = NotFound desc = "x"
        #7: kind: CREATE_STREAM, method: /intstore.IntStore/ListItems, ref index: 0
        #8: kind: SEND, method: , ref index: 7, message:
        #9: kind: RECV, method: , ref index: 7, message:
        name: "a"
        value: 1
        #10: kind: RECV, method: , ref index: 7, error: EOF
        #11: kind: CREATE_STREAM, method: /intstore.IntStore/SetStream, ref index: 0
        #12: kind: SEND, method: , ref index: 11, message:
        name: "b"
        value: 2
        #13: kind: SEND, method: , ref index: 11, message:
        name: "c"
        value: 3
        #14: kind: RECV, method: , ref index: 11, message:
        count: 2
        #15: kind: CREATE_STREAM, method: /intstore.IntStore/StreamChat, ref index: 0
        #16: kind: SEND, method: , ref index: 15, message:
        name: "d"
        value: 4
        #17: kind: RECV, method: , ref index: 15, message:
        name: "d"
        value: 4
        #18: kind: SEND, method: , ref index: 15, message:
        name: "e"
        value: 5
        #19: kind: RECV, method: , ref index: 15, message:
        name: "e"
        value: 5
        #20: kind: RECV, method: , ref index: 15, error: EOF
        
        want:
        initial state: "\x01\x02\x03"
        #1: kind: REQUEST, method: /intstore.IntStore/Set, ref index: 0, message:
        name:  "a"
        value:  1
        #2: kind: RESPONSE, method: , ref index: 1, message:
        #3: kind: REQUEST, method: /intstore.IntStore/Get, ref index: 0, message:
        name:  "a"
        #4: kind: RESPONSE, method: , ref index: 3, message:
        name:  "a"
        value:  1
        #5: kind: REQUEST, method: /intstore.IntStore/Get, ref index: 0, message:
        name:  "x"
        #6: kind: RESPONSE, method: , ref index: 5, error: rpc error: code = NotFound desc = "x"
        #7: kind: CREATE_STREAM, method: /intstore.IntStore/ListItems, ref index: 0
        #8: kind: SEND, method: , ref index: 7, message:
        #9: kind: RECV, method: , ref index: 7, message:
        name:  "a"
        value:  1
        #10: kind: RECV, method: , ref index: 7, error: EOF
        #11: kind: CREATE_STREAM, method: /intstore.IntStore/SetStream, ref index: 0
        #12: kind: SEND, method: , ref index: 11, message:
        name:  "b"
        value:  2
        #13: kind: SEND, method: , ref index: 11, message:
        name:  "c"
        value:  3
        #14: kind: RECV, method: , ref index: 11, message:
        count:  2
        #15: kind: CREATE_STREAM, method: /intstore.IntStore/StreamChat, ref index: 0
        #16: kind: SEND, method: , ref index: 15, message:
        name:  "d"
        value:  4
        #17: kind: RECV, method: , ref index: 15, message:
        name:  "d"
        value:  4
        #18: kind: SEND, method: , ref index: 15, message:
        name:  "e"
        value:  5
        #19: kind: RECV, method: , ref index: 15, message:
        name:  "e"
        value:  5
        #20: kind: RECV, method: , ref index: 15, error: EOF
        
FAIL
exit status 1
FAIL	github.com/google/go-replayers/grpcreplay	0.195s
```
The results on i686 are the same.
